export const small = "1em"
export const base = "2em"
export const medium = "3em"
export const large = "4em"
export const huge = "5em"

export const breakPoint = "950px"

export const pillHeight = "2.3em"
export const pillRadius = "1.15em"
export const pillWidth = "8.5em"
export const pillMobileWidth = "8em"
export const pageBottom = "12em"
export const containerWidth = "51.9em"
export const cardHeight = "14.8em"
export const cardMobileHeight = "20em"
