export const xxxSmall = "0.1em"
export const xxSmall = "0.25em"
export const xSmall = "0.5em"
export const small = "1em"
export const base = "2em"
export const medium = "3em"
export const large = "4em"
export const huge = "5em"
export const xHuge = "6em"
export const xxHuge = "8em"

export const breakPoint = "950px"
export const smallBreakPoint = "800px"

export const pillHeight = "2em"
export const pillRadius = "1em"
export const pillWidth = "8em"
export const pillMobileWidth = "8em"
export const pageBottom = "12em"
export const containerWidth = "54em"
export const cardHeight = "17em"
export const cardMobileHeight = "20em"
export const cardWidthLarge = "59%"
export const cardWidthSmall = "37.5%"
