export const xxSmall = "0.25em"
export const xSmall = "0.5em"
export const small = "1em"
export const base = "2em"
export const medium = "3em"
export const large = "4em"
export const huge = "5em"
export const xHuge = "6em"
export const xxHuge = "8em"

export const borderRadius = "0.2em"
export const breakPoint = "950px"
export const smallBreakPoint = "800px"

export const containerWidth = "63em"
export const largeContainerWidth = "81em"
export const cardHeight = "17em"
